proxy:
  port: 8080
  authentication: none
  admin-groups: admins
  hide-navbar: false
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
  - id: 01_probeshinyapp
    container-image: akiro/example-probeshinyapp
    # container-volumes: [ "/data/proj-1:/data/proj-1" ]
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
  container-log-path: ./config/container-logs

logging:
  file:
    shinyproxy.log

